### PR TITLE
Adds Magnet Player to FAQ

### PR DESCRIPTION
**Pull request by ferrolho**

### CODE REVIEW

**Comment by ferrolho** [comment]
Ahah! :P I want to finish this so I can start other projects, @DiegoRBaquero. Yes, let's wait for feross' approval.

**Comment by DiegoRBaquero** [comment]
@ferrolho What else are you working on? I'm looking for new projects to work on too

**Comment by ferrolho** [comment]
@DiegoRBaquero Nothing at the moment.. Classes start this Monday, so I guess I don't have much time left :(

**Comment by ferrolho** [comment]
@dcposch Thanks for the tip! I have changed it and I like it much better now :)

**Pull request merged**
