### PR TITLE
#411 Pick an available port on "listen EADDRINUSE" or "listen EACCES"

### PR DESCRIPTION
**Pull request by yciabaud**
Let the OS choose a port when the default or given one is used or unauthorized.
 
Fixes: #411

### CODE REVIEW

**Comment by yciabaud** [comment]
Sorry I believe I misunderstood PR process...

**Comment by joseph-onsip** [comment]
This looks good to me, but I wanted to make sure it could be tested automatically. I've added a ([failing](https://travis-ci.org/feross/webtorrent/builds/90017640#L876)) test on the [test-issue411](https://github.com/feross/webtorrent/tree/test-issue411) branch. Could you rebase your changes on top of that branch?

**Comment by yciabaud** [comment]
Thank you @joseph-onsip, I rebased my commits on your branch and the test looks good.

**Comment by joseph-onsip** [comment]
Looks great, thanks again!

**Pull request merged**
