### PR TITLE
Add new FAQ: "Does WebTorrent leak your IP address?"

### PR DESCRIPTION
**Pull request by feross**
Inspired by the thread here: https://www.reddit.com/r/WebTorrent/comments/52f3ns/since_webtorrent_uses_webrtc_does_it_leak_your_ip/

### CODE REVIEW

**Comment by dcposch** [comment]
WebRTC doesn't leak your IP if you're using a VPN, but it **does** leak your IP if you're using the browser proxy settings, right?

**Comment by feross** [comment]
> WebRTC doesn't leak your IP if you're using a VPN, but it does leak your IP if you're using a browser proxy, right?

I've never heard of this being the case. Link?

**Comment by DiegoRBaquero** [comment]
@dcposch @feross It shouldn't. See https://bugs.chromium.org/p/chromium/issues/detail?id=497040

**Comment by dcposch** [comment]
@DiegoRBaquero thanks. I remember seeing that bug. I think Firefox has the same issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=959893

Since it's an open bug in both Chrome and Firefox, we should mention that browser proxies won't help for now. You need a full VPN if you want to location/IP privacy.

**Comment by DiegoRBaquero** [comment]
@dcposch In Chrome it's actually fixed.

**Comment by feross** [comment]
Great, thanks for the investigation and discussion. Merging this now!

**Pull request merged**
