### PR TITLE
Add url to cinematrix.one

### PR DESCRIPTION
**Pull request by v0dy**
Added entry to cinematrix.one

### CODE REVIEW

**Comment by feross** [comment]
I took a look at your site. It looks like it only contains public domain, creative commons, legitimate content. Is your plan to keep it that way?

**Comment by v0dy** [comment]
Yes i will keep the content free! I will also add the sourcecode later on. 
Any suggestion for content is welcome!

**Comment by feross** [comment]
I'm hoping to spend some time compiling some free content into a github repo soon for a gallery I want to put together. We should collaborate on putting that together, and finding free sources. Related: https://github.com/feross/webtorrent-www/issues/27

**Comment by feross** [comment]
Can you update this PR and remove the reference to PT? I think that's not necessary -- your site has nothing to do with piracy.

**Comment by v0dy** [comment]
Yes! I was thinking about adding archive.org, vodo.net and CCC videos as project butter does but the problem is that there is no one seeding from a webtorrent client yet. 
Also updated PR.

**Comment by feross** [comment]
Yeah -- that's something I want to fix. For all the free content out there, I think we can raise a WebTorrent fund to seed it to web browsers.

Merged.

**Comment by v0dy** [comment]
Yeah that's a good idea, or get archive.org to seed them as they already host most of the video content via http. 

For now i will probably seed all the content on my site from a 100mbit connection, just need to set up a server with the webtorrent-client.

**Pull request closed without merging**
