### PR TITLE
Storage leakfix

### PR DESCRIPTION
**Pull request by astro**
For your consideration, attempts to solve #248

### CODE REVIEW

**Comment by astro** [comment]
Hmmm... something is breaking the fs-storage tests.

**Comment by astro** [comment]
Honestly, I would like to keep the piece backing buffer separated in blocks so we can persist them away ASAP, to lift pressure from the GC.

**Comment by astro** [comment]
I would like to know your opionion on the idea. I've got a preliminary implementation here:
https://github.com/astro/webtorrent/tree/per-block-buffers
Block structures cause quite some overhead, so we'll need different handling for pieces with a blank/written state. My experiment has shown really low memory usage by partially loaded pieces. This will benefit performance whenever we can move received data off memory, ie. to files or IndexedDB.

**Comment by feross** [comment]
Trying to debug why this causes the tests to fail.

**Comment by feross** [comment]
I couldn't figure out why the tests are failing, so I had to revert merging this. I'll take another look soon.

**Pull request merged**
