### PR TITLE
Max web conns default

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
After a lot of testing and profiling (because I was naive) I found that it's best to keep the concurrent connections small and rotate them as they become available.

This PR sets the maxWebConns to 4 by default. Making a webseed's max request vary from 1 to 4 depending on its speed & piece length.

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
It's safe to merge. Damn you AppVeyor.

**Comment by feross** [comment]
There's an even bigger issue that @dcposch and I just discovered with web seeds. PR incoming.

**Comment by feross** [comment]
https://github.com/feross/webtorrent/pull/723

**Comment by feross** [comment]
0.90.2

**Pull request merged**
