### PR TITLE
Update faq.md

### PR DESCRIPTION
**Pull request by FaCuZ**
Add TorrentMedia to "Who's Using" section of FAQ.

### CODE REVIEW

**Comment by feross** [comment]
Wow, nice!! Another desktop torrent app that can connect to web peers! WOOT!

cc WebTorrent Desktop contributors -- pretty sweet, I think we've achieved escape velocity 🚀 🚀  @dcposch @ungoldman @Flet @grunjol @demoneaux @mathiasvr @watson @codealchemist

**Comment by ungoldman** [comment]
w00t

**Comment by feross** [comment]
@FaCuZ Are you going to offer prebuilt binaries for users to download? Once you have those and a website, I bet that a news site like TorrentFreak would love to write about what you've built.

**Comment by codealchemist** [comment]
Nice!
@FaCuZ I see you added channels to your app.
I'll try it soon :)
Thanks for sharing!

**Comment by FaCuZ** [comment]
@feross Thanks. Yes, but when I finished the basic features. There are still things to do.

**Pull request merged**
