### PR TITLE
Added pause/resume, refactored code, improved command line interface (and more)

### PR DESCRIPTION
**Pull request by whitef0x0**
This is a big PR, so let me just list out everything that I've changed/added

#### Torrent.js
1. Added pause() & resume() for active torrents 
    - pauses and resumes the current torrent
2. Added disableSeeding() and enableSeeding()
    - enables or disables autoseeding 

#### Index.js
1. Added pause() & resume() 
   - pauses and resumes a client's torrent (calls Torrent.pause/resume)

#### bin/cmd.js
1. Added CLI menu to quit, resume and pause while seeding or downloading a torrent

#### test/browserAppendTo
1. Added a browser-based video streaming test for AppendTO

#### test/Resume-Torrent-Scenarios
1. Added 5 scenario-based test cases for pause and resume (resume-torrent-scenarios.js)

#### Torrent.js
1. Added unit tests for private functions in Torrent.js

I also added __coveralls__ support and code coverage with __istanbul__ if you choose to use it and I fixed formatting errors in the .travis.yml.

### CODE REVIEW

**Comment by rom1504** [comment]
I don't know about the rest, but I bet searching on kat is probably not okay to be in webtorrent and should be in an other repo that use webtorrent ;)

**Comment by whitef0x0** [comment]
I'll go ahead and remove the search.

**Comment by whitef0x0** [comment]
I've removed the search functionality for now.

**Comment by whitef0x0** [comment]
@feross have you been able to take a look at this?

**Comment by whitef0x0** [comment]
I've also removed the CLI part for test.js.

Is there anything else I should do @DiegoRBaquero

**Comment by DiegoRBaquero** [comment]
@whitef0x0 This PR is for @feross to decide. (I don't know what he is up to though because he hasn't been around the last few days)

In my opinion, I don't like disabling seeding option. BitTorrent is about sharing.

**Comment by niieani** [comment]
@DiegoRBaquero there are legitimate use cases for disabling seeding. BitTorrent is not only about end-user sharing, it's a technology for transferring data that can also be used by companies / enterprises, e.g. in low-end IoT devices that can't spare the power/connectivity required to seed.

**Comment by rom1504** [comment]
I think this would be better split into several PRs to make it easier to review it.
Also a lot of this can now move to a [webtorrent-cli](https://github.com/feross/webtorrent-cli) PR

**Comment by feross** [comment]
I appreciate that this PR must have taken a lot of effort to put together, but there are lots of problems with it.

- Each change should be sent as a separate PR so it can be reviewed independently. Giant PRs are overwhelming to review and have to be accepted all-or-nothing.
- In the future, you should probably create an issue to discuss the features you want to add before doing a bunch of work. Because features like these are a no-go:
  - Hardcoding urls to external services. WebTorrent is an un-opinionated torrent client and we're not ever going to include third-party search.
  - Disabling web seeding is not a use case that we're going to support out of the box. In the future, we hope to allow custom "strategies" in addition to the built in ones: `sequential` and `rarest-first`. That's the place where a user could disable seeding if they need it for IoT.
- No `bower.json`. Bower is an anti-pattern.
- Don't update the minified build – that's done at release tie.

**Pull request closed without merging**
