### PR TITLE
Adding property for downloaded bytes per file.

### PR DESCRIPTION
**Pull request by mikeal**
Needed this in an app I've been building. It's almost the same as the property on the full torrent.

### CODE REVIEW

**Comment by vankasteelj** [comment]
I second this, I need it too. `torrent.files[<index>].downloaded` is an API call I spent too much time trying to find x)

**Comment by mikeal** [comment]
Is this going to get merged soon or should I deploy with a fork for a while until it is?

**Comment by feross** [comment]
Released as 0.98.0. Sorry for the delay.

**Comment by vankasteelj** [comment]
Awesome, thanks

**Pull request merged**
