### PR TITLE
Added an app built with Webtorrent

### PR DESCRIPTION
**Pull request by alexeisavca**
Can I haz my app mentioned here pls?

### CODE REVIEW

**Comment by feross** [comment]
Wow! This is amazing!! Reminds me of [PeerCDN](http://www.peercdn.com). Good work :-)

**Comment by feross** [comment]
Just realized the name "webtorrentapp" might be confusing since we're going to be releasing [WebTorrent.app](https://github.com/feross/webtorrent.app) soon.

**Comment by alexeisavca** [comment]
I guess I can think of a new name.
tbh "webtorrenapp" just was the first thing that popped into my mind.

**Comment by feross** [comment]
Not a huge deal, but just wanted to let you know :cat2:

**Pull request merged**
