### PR TITLE
Make WTGC description more clear

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
[Git.io](https://git.io) is not a "3rd part service", it is [official](https://github.com/blog/985-git-io-github-url-shortener) GitHub URL shortener. Many projects use it.

**Comment by DiegoRBaquero** [comment]
Ohhh, didn't know that. Well, can you keep to original to maintain consistency?

**Comment by FluorescentHallucinogen** [comment]
I want to use this short vanity git.io URL everywhere. Is it a problem? If yes, I can change it to full URL.

**Comment by DiegoRBaquero** [comment]
It's cool :)

**Comment by FluorescentHallucinogen** [comment]
@DiegoRBaquero, @feross 
FYI, https://git.io/webtorrent. :wink:

**Comment by FluorescentHallucinogen** [comment]
@DiegoRBaquero, @feross
Please update https://webtorrent.io/faq page too.

**Comment by feross** [comment]
@FluorescentHallucinogen That gets updated the next time the site is built. I'll kick off a build.

**Pull request merged**
