### PR TITLE
Added web2web to the "Who is using" section

### PR DESCRIPTION
**Pull request by elendirx**
Added my project called web2web to the "Who is using" FAQ section.

### CODE REVIEW

**Comment by feross** [comment]
@elendirx Awesome work! Do you mind linking directly to your [demo site](https://elendirx.github.io/web2web/) and making the github link say "source code" like the others?

**Comment by elendirx** [comment]
@feross Sure, I added the source code link. Thanks!

**Comment by feross** [comment]
Nice!

**Comment by feross** [comment]
Btw, I posted about your project [on Hacker News](https://news.ycombinator.com/item?id=12502029) and [on Twitter](https://twitter.com/feross/status/776198442003509248). Noticed you have nearly 500 GitHub stars now. Nice, looks like there's real interest in this idea!!

There have been previous attempts at this idea, but none have taken off yet.

This is kind of like BitTorrent Inc.'s "Maelstrom" project, or even ZeroNet, but it works on today's web instead of requiring the user to install a new browser on their computer. You can also provide additional seeders to your website by seeding it from a desktop torrent client that supports WebTorrent (like WebTorrent Desktop). Very neat!

**Comment by elendirx** [comment]
So that's where all the stars are coming from! Thanks for posting. But more important, thanks for your work on Webtorrent, it's a beautiful project.

**Comment by feross** [comment]
Thanks :)

**Pull request merged**
