### PR TITLE
Vique added

### PR DESCRIPTION
**Pull request by andreapaiola**

### CODE REVIEW

**Comment by feross** [comment]
Thanks! Looks like the start of a really cool app.

Btw, the magnet link that's preloaded in the app didn't work for me. Is it seeded? If you want, you're free to use the the Sintel (creative-commons licensed) torrrent.

The magnet link is: magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.webtorrent.io&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4

Also, it appears that when a torrent is stuck and doesn't start playing, that there's no way to skip to the next torrent in the list. Am I missing something? That would be cool to add!

**Comment by andreapaiola** [comment]
Yeah... The magnet links are posted by users, sadly zero seeders for most of them...
My hope is/was that sharing users video in the queue will increase the number of valid webtorrent magnet links.

The Sintel is in the queue but it's not the first.

It's a great idea, I'll add the skip button ASAP!

**Comment by feross** [comment]
@andreapaiola Cool, let me know once you've added it! I want to check it out :)

**Comment by andreapaiola** [comment]
Hi Feross,

- added a GO link in the "next video area"
- added a SKIP link in the "waiting area"
- updated webtorrent version to 0.74.2 here and in the Niagara Project

Stats: 20 days online, 60 magnet links in the queue (and Sintel is the fourth https://andreapaiola.name/vique/?v=6a9759bffd5c0af65319979fb7832189f4f3c35d  )

**Comment by feross** [comment]
Nice, seems to work great!

**Pull request merged**
